export const states = [
  { id: "AB", description: "Alberta" },
  { id: "BC", description: "British Columbia" },
  { id: "MB", description: "Manitoba" },
  { id: "NB", description: "New Brunswick" },
  { id: "NL", description: "Newfoundland and Labrador" },
  { id: "NS", description: "Nova Scotia" },
  { id: "NT", description: "Northwest Territories" },
  { id: "NU", description: "Nunavut" },
  { id: "ON", description: "Ontario" },
  { id: "PE", description: "Prince Edward Island" },
  { id: "QC", description: "Quebec" },
  { id: "SK", description: "Saskatchewan" },
  { id: "YT", description: "Yukon" },
];

export type Contact = {
  id: number;
  firstname: string;
  lastname: string;
  date_of_birth: string;
  email_address: string;
  phone_number: string;
  street_address: string;
  city: string;
  state: string;
  zip_code: string;
};
export const contactsData: Contact[] = [
  {
    id: 1,
    firstname: "John",
    lastname: "Doe",
    date_of_birth: "1990-01-01",
    email_address: "john@example.com",
    phone_number: "1234567890",
    street_address: "123 Street",
    city: "City",
    state: "ON",
    zip_code: "12345",
  },
  {
    id: 2,
    firstname: "Jane",
    lastname: "Smith",
    date_of_birth: "1985-05-12",
    email_address: "jane@example.com",
    phone_number: "9876543210",
    street_address: "456 Avenue",
    city: "Town",
    state: "ON",
    zip_code: "67890",
  },
  {
    id: 3,
    firstname: "Alice",
    lastname: "Johnson",
    date_of_birth: "1992-07-25",
    email_address: "alice.j@example.com",
    phone_number: "3216549870",
    street_address: "789 Boulevard",
    city: "Village",
    state: "ON",
    zip_code: "11223",
  },
  {
    id: 4,
    firstname: "Bob",
    lastname: "Brown",
    date_of_birth: "1980-03-14",
    email_address: "bob@example.com",
    phone_number: "6549873210",
    street_address: "135 Road",
    city: "Cityville",
    state: "ON",
    zip_code: "33445",
  },
  {
    id: 5,
    firstname: "Charlie",
    lastname: "Davis",
    date_of_birth: "1995-09-08",
    email_address: "charlie.d@example.com",
    phone_number: "7531594860",
    street_address: "246 Drive",
    city: "Metropolis",
    state: "ON",
    zip_code: "55667",
  },
  {
    id: 6,
    firstname: "Dana",
    lastname: "Miller",
    date_of_birth: "1988-02-20",
    email_address: "dana.m@example.com",
    phone_number: "3692581470",
    street_address: "369 Parkway",
    city: "Suburbia",
    state: "ON",
    zip_code: "77889",
  },
  {
    id: 7,
    firstname: "Eve",
    lastname: "Wilson",
    date_of_birth: "1991-06-11",
    email_address: "eve.w@example.com",
    phone_number: "4823690517",
    street_address: "486 Court",
    city: "Lakeside",
    state: "ON",
    zip_code: "99001",
  },
  {
    id: 8,
    firstname: "Frank",
    lastname: "Moore",
    date_of_birth: "1983-11-22",
    email_address: "frank.m@example.com",
    phone_number: "2958741630",
    street_address: "521 Crescent",
    city: "Springfield",
    state: "ON",
    zip_code: "12356",
  },
  {
    id: 9,
    firstname: "Grace",
    lastname: "Taylor",
    date_of_birth: "1990-10-04",
    email_address: "grace.t@example.com",
    phone_number: "6029138475",
    street_address: "312 Hilltop",
    city: "Greenfield",
    state: "NB",
    zip_code: "23467",
  },
  {
    id: 10,
    firstname: "Hank",
    lastname: "Anderson",
    date_of_birth: "1987-12-15",
    email_address: "hank.a@example.com",
    phone_number: "5084739261",
    street_address: "753 Ridge",
    city: "Hillside",
    state: "NT",
    zip_code: "34578",
  },
  {
    id: 11,
    firstname: "Ivy",
    lastname: "Thomas",
    date_of_birth: "1993-04-09",
    email_address: "ivy.t@example.com",
    phone_number: "1346798520",
    street_address: "684 Valley",
    city: "Forest",
    state: "QC",
    zip_code: "45689",
  },
  {
    id: 12,
    firstname: "Jack",
    lastname: "Jackson",
    date_of_birth: "1986-08-30",
    email_address: "jack.j@example.com",
    phone_number: "2178493560",
    street_address: "936 Bridge",
    city: "Rivercity",
    state: "ON",
    zip_code: "56790",
  },
  {
    id: 13,
    firstname: "Kim",
    lastname: "White",
    date_of_birth: "1994-01-12",
    email_address: "kim.w@example.com",
    phone_number: "5612378940",
    street_address: "453 Oak",
    city: "Cityland",
    state: "NL",
    zip_code: "67801",
  },
  {
    id: 14,
    firstname: "Leo",
    lastname: "Martinez",
    date_of_birth: "1982-10-16",
    email_address: "leo.m@example.com",
    phone_number: "9284736150",
    street_address: "674 Maple",
    city: "Lakeshore",
    state: "AB",
    zip_code: "78912",
  },
  {
    id: 15,
    firstname: "Mia",
    lastname: "Garcia",
    date_of_birth: "1996-05-05",
    email_address: "mia.g@example.com",
    phone_number: "3476510987",
    street_address: "198 River",
    city: "Mountainview",
    state: "YT",
    zip_code: "89023",
  },
  {
    id: 16,
    firstname: "Nathan",
    lastname: "Martinez",
    date_of_birth: "1984-12-30",
    email_address: "nathan.m@example.com",
    phone_number: "7416529380",
    street_address: "289 Highland",
    city: "Windycity",
    state: "NS",
    zip_code: "12367",
  },
  {
    id: 17,
    firstname: "Olivia",
    lastname: "Clark",
    date_of_birth: "1991-02-22",
    email_address: "olivia.c@example.com",
    phone_number: "4802951743",
    street_address: "567 Park",
    city: "Sunnytown",
    state: "MB",
    zip_code: "23478",
  },
  {
    id: 18,
    firstname: "Paul",
    lastname: "Rodriguez",
    date_of_birth: "1989-07-03",
    email_address: "paul.r@example.com",
    phone_number: "1596243780",
    street_address: "894 Parkway",
    city: "Westend",
    state: "NT",
    zip_code: "34589",
  },
  {
    id: 19,
    firstname: "Quinn",
    lastname: "Hernandez",
    date_of_birth: "1981-05-17",
    email_address: "quinn.h@example.com",
    phone_number: "9632581470",
    street_address: "1236 Street",
    city: "Greenvalley",
    state: "BC",
    zip_code: "45690",
  },
  {
    id: 20,
    firstname: "Rachel",
    lastname: "Lewis",
    date_of_birth: "1988-04-29",
    email_address: "rachel.l@example.com",
    phone_number: "2589476310",
    street_address: "981 Bay",
    city: "Baytown",
    state: "SK",
    zip_code: "56701",
  },
  {
    id: 21,
    firstname: "Sam",
    lastname: "Young",
    date_of_birth: "1993-01-20",
    email_address: "sam.y@example.com",
    phone_number: "7418529630",
    street_address: "111 Pine",
    city: "Brighton",
    state: "NL",
    zip_code: "67812",
  },
  {
    id: 22,
    firstname: "Tina",
    lastname: "Scott",
    date_of_birth: "1990-03-12",
    email_address: "tina.s@example.com",
    phone_number: "6543217890",
    street_address: "222 Creek",
    city: "Lakewood",
    state: "PE",
    zip_code: "78923",
  },
  {
    id: 23,
    firstname: "Ursula",
    lastname: "King",
    date_of_birth: "1987-06-07",
    email_address: "ursula.k@example.com",
    phone_number: "3749256180",
    street_address: "333 Trail",
    city: "Woodlands",
    state: "QC",
    zip_code: "89034",
  },
  {
    id: 24,
    firstname: "Victor",
    lastname: "Wright",
    date_of_birth: "1985-09-13",
    email_address: "victor.w@example.com",
    phone_number: "6213985740",
    street_address: "444 Spring",
    city: "Sunnydale",
    state: "ON",
    zip_code: "90145",
  },
  {
    id: 25,
    firstname: "Will",
    lastname: "Green",
    date_of_birth: "1992-11-17",
    email_address: "will.g@example.com",
    phone_number: "8524697301",
    street_address: "555 Terrace",
    city: "Valleycity",
    state: "AB",
    zip_code: "12356",
  },
  {
    id: 26,
    firstname: "Xander",
    lastname: "Smith",
    date_of_birth: "1987-04-25",
    email_address: "xander.smith@example.com",
    phone_number: "6748294012",
    street_address: "879 Parkway",
    city: "Cedarwood",
    state: "BC",
    zip_code: "23411",
  },
  {
    id: 27,
    firstname: "Yasmin",
    lastname: "Lee",
    date_of_birth: "1990-06-09",
    email_address: "yasmin.lee@example.com",
    phone_number: "5498271610",
    street_address: "340 Elm",
    city: "Snowtown",
    state: "YT",
    zip_code: "67832",
  },
  {
    id: 28,
    firstname: "Zoe",
    lastname: "Taylor",
    date_of_birth: "1994-12-15",
    email_address: "zoe.taylor@example.com",
    phone_number: "6741902583",
    street_address: "748 Oak",
    city: "Brookville",
    state: "SK",
    zip_code: "78965",
  },
  {
    id: 29,
    firstname: "Adam",
    lastname: "Evans",
    date_of_birth: "1989-03-17",
    email_address: "adam.evans@example.com",
    phone_number: "3485721901",
    street_address: "623 Pine",
    city: "Parkland",
    state: "QC",
    zip_code: "23456",
  },
  {
    id: 30,
    firstname: "Bella",
    lastname: "Wilson",
    date_of_birth: "1992-01-29",
    email_address: "bella.wilson@example.com",
    phone_number: "4913028765",
    street_address: "853 Cedar",
    city: "Hillsview",
    state: "PE",
    zip_code: "34567",
  },
  {
    id: 31,
    firstname: "Cory",
    lastname: "Johnson",
    date_of_birth: "1985-11-10",
    email_address: "cory.johnson@example.com",
    phone_number: "6281947052",
    street_address: "412 Birch",
    city: "Clearwater",
    state: "NL",
    zip_code: "45678",
  },
  {
    id: 32,
    firstname: "Dylan",
    lastname: "Martin",
    date_of_birth: "1993-04-05",
    email_address: "dylan.martin@example.com",
    phone_number: "2053179864",
    street_address: "865 Ash",
    city: "Eastwood",
    state: "MB",
    zip_code: "56789",
  },
  // More entries follow the same pattern...
  {
    id: 100,
    firstname: "Chris",
    lastname: "Rogers",
    date_of_birth: "1990-08-12",
    email_address: "chris.rogers@example.com",
    phone_number: "9023458761",
    street_address: "389 Maple",
    city: "Seaview",
    state: "ON",
    zip_code: "89012",
  },
];
